---
title: "R Notebook"
output: html_notebook
---

1.1 Registro de notas de 5 estudiantes en vectore
```{r}
student_1 <- c(50.4, 62.3, 92.1, 77.6, TRUE)
student_2 <- c(41.7, 87.9, 75.3, 72.4, FALSE)
student_3 <- c(30.3, 67.8, 69.3, 71.2, FALSE)
student_4 <- c(65.4, 85.1, 92.3, 96.8, TRUE)
student_5 <- c(70.4, 88.2, 95.2, 90.7, TRUE)

student_1
student_2
student_3
student_4
student_5
```
1.2 Vector de estudiantes
```{r}
students_vector <- c(student_1, student_2, student_3, student_4, student_5)
students_vector

```
1.3 Matriz de estudiantes
```{r}
students_matrix <- matrix(students_vector, byrow=TRUE, nrow=5)
students_matrix

```
Nombrado de una Matriz
2.1 creación de vectores 
```{r}
name_students <- c("Lily Brown", "Davis Moore", "Susan Taylor", "Mike Jones",
"Tom Hill")
name_students

name_courses_legal_age <- c("TIC", "Accounting", "Psychology", "Ethics",
"Legal_age")
name_courses_legal_age
```

2.2 nombrado de filas y columnas de la matriz students_matrix
```{r}
colnames(students_matrix) <- name_courses_legal_age
rownames(students_matrix) <- name_students

students_matrix
```
rowSums, cbind
3.1 
